name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'sbt'

    - uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Build
      run: sbt compile
